source'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!

target:ZK_OnlyOne_Project do
    
    pod 'MJRefresh'
    pod 'AFNetworking'
    pod 'WRNavigationBar'
    pod 'Masonry'
    pod 'YYModel'
    pod 'WSProgressHUD'
    pod 'MJExtension'
    pod 'zhUITableViewAnimations'
end
