source'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!

target:ZK_OnlyOne_Project do
    
    pod 'MJRefresh'
    pod 'AFNetworking'
    pod 'Masonry'
    pod 'YYModel'
    pod 'WSProgressHUD'
    pod 'MJExtension'
    pod 'zhUITableViewAnimations'
    pod 'SDWebImage'
    pod 'SDWebImage/GIF'
    pod 'GKNavigationBarViewController'
    pod 'TXLiteAVSDK_Player'  # 腾讯云播放器-独立播放器版
    pod 'GKMessageTool'
    pod 'WRNavigationBar'
    pod 'ICPagingManager'
    pod 'SDCycleScrollView'
end
